[mdzk]
backlinks-header = "Backlinks"
authors = ["Ramos Aparicio"]
language = "es"
multilingual = false
src = "ğŸ§  brain"
title = "ğŸ§  Brain"
ignore = [
    "ğŸ§  Brain/300 - ğŸ—„ï¸ Resources/370 - ğŸ›• Templates",
    "ğŸ§  Brain/.obsidian/",
]

[output.html]
site-url = "/brain"
no-section-label = true

[output.html.fold]
enable = true
